In [1]:
x = ("Harsh", "Dhruv", "Nihar")
print(x)

('Harsh', 'Dhruv', 'Nihar')

In [2]:
print(len(x))

3

In [3]:
print(type(x))

<class 'tuple'>

In [5]:
y = tuple(("Jay", "Utkarsh", "devansu"))
print(y)

('Jay', 'Utkarsh', 'devansu')

In [6]:
mytuple = ("harsh", "Jay", "Utkarsh", "Nihar", "Dhruv")
print(mytuple[1])
print(mytuple[0])
print(mytuple[-1])

Jay
harsh
Dhruv

In [7]:
print(mytuple[1:4])

('Jay', 'Utkarsh', 'Nihar')

In [8]:
print(mytuple[2:])
print(mytuple[:3])

('Utkarsh', 'Nihar', 'Dhruv')
('harsh', 'Jay', 'Utkarsh')

In [11]:
print(x)

('Harsh', 'Dhruv', 'Nihar')

In [12]:
mytuple = ("harsh", "Jay", "Utkarsh", "Nihar", "Dhruv")
if "harsh" in mytuple:
    print("yes")

yes

In [13]:
x = ("Utkarsh", "Nihar", "Dhruv")
y = list(x)
y[1] = "Harsh"
x = tuple(y)

print(x)

('Utkarsh', 'Harsh', 'Dhruv')

In [15]:
x = ('Utkarsh', 'Harsh', 'Dhruv')
y = list(x)
y.append("Nihar")
x = tuple(y)
print(x)

('Utkarsh', 'Harsh', 'Dhruv', 'Nihar')

In [16]:
x = ('Utkarsh', 'Harsh', 'Dhruv')
y = list(x)
y.remove("Utkarsh")
x = tuple(y)
print(x)

('Harsh', 'Dhruv')

In [18]:
Names = ("harsh", "Jay", "Utkarsh", "Nihar", "Dhruv")

(more, patel, *modi) = Names

print(more)
print(patel)
print(modi)

harsh
Jay
['Utkarsh', 'Nihar', 'Dhruv']

In [19]:
thistuple = ("dhruv", "Jay", "Nihar")
for x in thistuple:
  print(x)

dhruv
Jay
Nihar

In [21]:
thistuple = ("dhruv", "Jay", "Nihar")
for i in range(len(thistuple)):
  print(thistuple[i])

dhruv
Jay
Nihar

In [24]:
thistuple = ("dhruv", "Jay", "Nihar")
i = 0

while i < len(thistuple):
  print(thistuple[i])
  i = i+1

dhruv
Jay
Nihar

In [25]:
t1 = ("H", "A", "R", "S", "H")
t2 = (1, 2, 3, 4)

t3 = t1 + t2
print(t3)

('H', 'A', 'R', 'S', 'H', 1, 2, 3, 4)

In [27]:
t1 = ("H", "A", "R", "S", "H")

t3 = t1 * 2
print(t3)

('H', 'A', 'R', 'S', 'H', 'H', 'A', 'R', 'S', 'H')